name: 'md2pdf'
description: 'Convert Markdown files to PDF'

inputs:
  file_dir:
    description: "The path of the markdown files."
    required: true
  output_dir:
    description: "The output path where you want to put the generated pdf."
    required: false
    default: output
  output_file_name:
    description: "The output file name"
    required: false
    default: output.pdf
  style_path:
    description: "The path of css stylsheet"
    required: false
    default:  style.css
    
    
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Merge markdown files
      shell: bash
      run: cat ${{ inputs.file_dir }}/*.md > ${{ inputs.file_dir }}/output.md
    - name: Convert to PDF 
      shell: bash
      run: npx mdpdf ${{ inputs.file_dir }}/output.md ${{ inputs.output_dir }}/${{ inputs.output_file_name }} --style ${{ inputs.style_path}} 
